[build]
command = "pip install -r functions/requirements.txt"
publish = "static"                                                                      functions = "functions"

[dev]
command = "netlify-lambda serve functions"
